# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'Alamofire', '~> 4.5.1'
  pod 'TwitterKit'
  pod 'SwiftyJSON', '~> 4.0 '
  # Pods for TwitterApp

  target 'TwitterAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwitterAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
